### ISSUE TITLE
OpenAI API key should not be required

### ISSUE THREAD

**Issue by danielz02** [AI-secure/DecodingTrust#13]
**Describe the bug**
Reported by AMD. Errors are encountered before any GPU related kicking in, all seem to be python packages, version and usage/reference README related…. I would assume the same errors on Ubuntu 20.04 + Nvidia RTX 4090, yet to confirm though.

```bash
root@Zach-WS:/dockerx/DecodingTrust#
root@Zach-WS:/dockerx/DecodingTrust# ll /data/llama2-7b-chat/               [Note, llama2-7b model stored local was converted to HF]
total 13163420
drwxr-xr-x 2 1002 1002       4096 Oct  8 23:22 ./
drwxr-xr-x 3 root root       4096 Oct  8 23:18 ../
-rwxrwxr-x 1 1002 1002        562 Oct  8 23:20 config.json*
-rwxrwxr-x 1 1002 1002        116 Oct  8 23:20 generation_config.json*
-rwxrwxr-x 1 1002 1002 9976620122 Oct  8 23:22 pytorch_model-00001-of-00002.bin*
-rwxrwxr-x 1 1002 1002 3500310787 Oct  8 23:22 pytorch_model-00002-of-00002.bin*
-rwxrwxr-x 1 1002 1002      23950 Oct  8 23:22 pytorch_model.bin.index.json*
-rwxrwxr-x 1 1002 1002        411 Oct  8 23:22 special_tokens_map.json*
-rwxrwxr-x 1 1002 1002    1842767 Oct  8 23:22 tokenizer.json*
-rwxrwxr-x 1 1002 1002     499723 Oct  8 23:22 tokenizer.model*
-rwxrwxr-x 1 1002 1002        745 Oct  8 23:22 tokenizer_config.json*
root@Zach-WS:/dockerx/DecodingTrust#
root@Zach-WS:/dockerx/DecodingTrust#
root@Zach-WS:/dockerx/DecodingTrust# HYDRA_FULL_ERROR=1 dt-run +ood=knowledge_2020_5shot ++model="hf//data/llama2-7b-chat/" ++conv_template="vicuna_v1.1" ++model_loader=HF ++torch_dtype=BFLOAT16 ++task=\[sst2\]
sys:1: UserWarning: 
'config' is validated against ConfigStore schema with the same name.
This behavior is deprecated in Hydra 1.1 and will be removed in Hydra 1.2.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/automatic_schema_matching for migration instructions.       
/opt/conda/envs/py_3.9/lib/python3.9/site-packages/hydra/main.py:94: UserWarning: 
'config' is validated against ConfigStore schema with the same name.
This behavior is deprecated in Hydra 1.1 and will be removed in Hydra 1.2.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/automatic_schema_matching for migration instructions.       
  _run_hydra(
Pricing: 0.002 / 1k tokens
AutoClient: cache_path = ./.cache/tmp89nkdlrh
AutoClient: mongo_uri =
/dockerx/DecodingTrust/src/dt/chat.py:324: UserWarning: Argument 'conv_template' ignored for OpenAI models    
  warnings.warn("Argument 'conv_template' ignored for OpenAI models")
  0%|                                                                                 | 0/100 [00:00<?, ?it/s]Created cache with config: SqliteCacheConfig(path='./.cache/tmp89nkdlrh/openai.sqlite')

Traceback (most recent call last):
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/retrying.py", line 251, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/helm/proxy/clients/auto_client.py", line 181, in make_request_with_retry
    return client.make_request(request)
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/helm/proxy/clients/openai_client.py", line 41, in make_request
    raise ValueError("OpenAI API key is required")
ValueError: OpenAI API key is required

Request failed. Retrying (attempt #2) in 0 seconds... (See above for error details)

```
**To Reproduce**

```bash
dt-run +ood=knowledge_2020_5shot ++model="hf//data/llama2-7b-chat/" ++conv_template="vicuna_v1.1" ++model_loader=HF ++torch_dtype=BFLOAT16 ++task=\[sst2\]
```

**Expected behavior**
OpenAI API key should not be required when using non-HF models.

**Environment:**
 - Container

**Comment by danielz02** [comment]
The team assumed the configuration structure of the main branch while used the code for feature branch.
